name: Publish to PyPI & GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install poetry twine
      
      - name: Clean previous builds
        run: rm -rf dist/

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
      # - name: Publish to GitHub Packages
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://upload.pypi.org/legacy/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          name: "${{ github.ref_name }}"
          body: "Automatically generated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
