name: Publish to PyPI & GitHub Packages

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/runllama/
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install poetry twine
      
      - name: Clean previous builds
        run: rm -rf dist/

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish

      - name: Publish to GitHub Packages
        run: |
          poetry config repositories.github https://upload.pypi.org/legacy/
          poetry publish --repository github

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          name: "Release ${{ github.ref_name }}"
          body: "Automatically generated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
