name: Run Pytest

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      packages: write
      contents: read
    services:
      ollama:
        image: ollama/ollama:0.5.7
        ports:
          - 11434:11434
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run test
        run: poetry run pytest -v tests/test_*
